webtalk_init -webtalk_dir D:\\sram_test\\sram_sip_2\\sram_sip\\sram_sip.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期三 一月 16 20:21:20 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s1a1s7hj5vkhqql367dv13r7ss" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.1_30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1547640977048" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.1" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1547640977048"
webtalk_add_data -client sdk -key uid -value "1547641021748" -context "sdk\\\\bsp/1547641021748"
webtalk_add_data -client sdk -key hwid -value "1547640977048" -context "sdk\\\\bsp/1547641021748"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1547641021748"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1547641021748"
webtalk_add_data -client sdk -key uid -value "1547641054068" -context "sdk\\\\application/1547641054068"
webtalk_add_data -client sdk -key hwid -value "1547640977048" -context "sdk\\\\application/1547641054068"
webtalk_add_data -client sdk -key bspid -value "1547641021748" -context "sdk\\\\application/1547641054068"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1547641054068"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1547641054068"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1547641054068"
webtalk_transmit -clientid 3516697025 -regid "" -xml D:\\sram_test\\sram_sip_2\\sram_sip\\sram_sip.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\sram_test\\sram_sip_2\\sram_sip\\sram_sip.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\sram_test\\sram_sip_2\\sram_sip\\sram_sip.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
